apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      containers:
      - name: finance-container
        image: snehaldhul/finance-image:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: finance-service
spec:
  type: NodePort
  selector:
    app: finance
  ports:
    - protocol: TCP
      port: 8081       # Service port
      targetPort: 8081 # Container port
      nodePort: 30081  # External port on the node (30000–32767)
